// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TbspRpgDataLayer;

#nullable disable

namespace TbspRpgDataLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251220205549_AddLanguagesAndCopy")]
    partial class AddLanguagesAndCopy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AdventureLanguage", b =>
                {
                    b.Property<int>("AdventuresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdventuresId", "LanguagesId");

                    b.HasIndex("LanguagesId");

                    b.ToTable("AdventureLanguage");
                });

            modelBuilder.Entity("AdventureObjectLocation", b =>
                {
                    b.Property<int>("AdventureObjectsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdventureObjectsId", "LocationsId");

                    b.HasIndex("LocationsId");

                    b.ToTable("AdventureObjectLocation");
                });

            modelBuilder.Entity("ScriptScript", b =>
                {
                    b.Property<int>("IncludedInId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncludesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IncludedInId", "IncludesId");

                    b.HasIndex("IncludesId");

                    b.ToTable("ScriptScript");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Adventure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DescriptionSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitialSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitializationScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TerminationScriptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InitializationScriptId");

                    b.HasIndex("TerminationScriptId");

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.AdventureObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActionScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DescriptionSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitializationScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NameSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionScriptId");

                    b.HasIndex("AdventureId");

                    b.HasIndex("InitializationScriptId");

                    b.ToTable("AdventureObjects");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.AdventureObjectGameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdventureObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdventureObjectState")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdventureObjectId");

                    b.HasIndex("GameId");

                    b.ToTable("AdventureObjectGameStates");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Copy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ScriptId");

                    b.ToTable("Copy");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocationUpdateTimeStamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("LocationId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.LanguageSources.En", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.ToTable("SourcesEn");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.LanguageSources.Esp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.ToTable("SourcesEsp");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnterScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Final")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Initial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("EnterScriptId");

                    b.HasIndex("ExitScriptId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RouteTakenScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouteTakenSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RouteTakenScriptId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdventureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("Content");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("AdventureLanguage", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Adventure", null)
                        .WithMany()
                        .HasForeignKey("AdventuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdventureObjectLocation", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.AdventureObject", null)
                        .WithMany()
                        .HasForeignKey("AdventureObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptScript", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Script", null)
                        .WithMany()
                        .HasForeignKey("IncludedInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Script", null)
                        .WithMany()
                        .HasForeignKey("IncludesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Adventure", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Script", "InitializationScript")
                        .WithMany("AdventureInitializations")
                        .HasForeignKey("InitializationScriptId");

                    b.HasOne("TbspRpgDataLayer.Entities.Script", "TerminationScript")
                        .WithMany("AdventureTerminations")
                        .HasForeignKey("TerminationScriptId");

                    b.Navigation("InitializationScript");

                    b.Navigation("TerminationScript");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.AdventureObject", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Script", "ActionScript")
                        .WithMany()
                        .HasForeignKey("ActionScriptId");

                    b.HasOne("TbspRpgDataLayer.Entities.Adventure", "Adventure")
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Script", "InitializationScript")
                        .WithMany()
                        .HasForeignKey("InitializationScriptId");

                    b.Navigation("ActionScript");

                    b.Navigation("Adventure");

                    b.Navigation("InitializationScript");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.AdventureObjectGameState", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.AdventureObject", "AdventureObject")
                        .WithMany("AdventureObjectGameStates")
                        .HasForeignKey("AdventureObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Game", "Game")
                        .WithMany("AdventureObjectGameStates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdventureObject");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Content", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Game", "Game")
                        .WithMany("Contents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Copy", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Language", "Language")
                        .WithMany("Copy")
                        .HasForeignKey("LanguageId");

                    b.HasOne("TbspRpgDataLayer.Entities.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId");

                    b.Navigation("Language");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Game", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Adventure", "Adventure")
                        .WithMany("Games")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Location", "Location")
                        .WithMany("Games")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.LanguageSources.En", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.LanguageSources.Esp", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Location", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Adventure", "Adventure")
                        .WithMany("Locations")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Script", "EnterScript")
                        .WithMany()
                        .HasForeignKey("EnterScriptId");

                    b.HasOne("TbspRpgDataLayer.Entities.Script", "ExitScript")
                        .WithMany()
                        .HasForeignKey("ExitScriptId");

                    b.Navigation("Adventure");

                    b.Navigation("EnterScript");

                    b.Navigation("ExitScript");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Route", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Location", "Location")
                        .WithMany("Routes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TbspRpgDataLayer.Entities.Script", "RouteTakenScript")
                        .WithMany()
                        .HasForeignKey("RouteTakenScriptId");

                    b.Navigation("DestinationLocation");

                    b.Navigation("Location");

                    b.Navigation("RouteTakenScript");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Script", b =>
                {
                    b.HasOne("TbspRpgDataLayer.Entities.Adventure", "Adventure")
                        .WithMany("Scripts")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Adventure", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Locations");

                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.AdventureObject", b =>
                {
                    b.Navigation("AdventureObjectGameStates");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Game", b =>
                {
                    b.Navigation("AdventureObjectGameStates");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Language", b =>
                {
                    b.Navigation("Copy");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Location", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("TbspRpgDataLayer.Entities.Script", b =>
                {
                    b.Navigation("AdventureInitializations");

                    b.Navigation("AdventureTerminations");
                });
#pragma warning restore 612, 618
        }
    }
}
